YOLO_MODEL_PATH = "models/yolo11s.pt"
OPTIONAL_YOLO_MODEL_PATH = "models/yolo11m.pt"
HAND_LANDMARKER_MODEL_PATH = "models/hand_landmarker.task"

CAMERA_SOURCE = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

CONFIDENCE_THRESHOLD = 0.5
IMAGE_SIZE = 640

DEVICE = "auto"
USE_GPU = True
FACE_ONLY_MODE = True

SHOW_FPS = True
SHOW_DEVICE = True
SHOW_FACE_BOX = True
SHOW_HAND_LANDMARKS = True
SHOW_GESTURE_NAME = False
SHOW_WINDOW = True
SHOW_PROGRESS_BAR = True

SAVE_SCREENSHOT = False
SAVE_VIDEO = False

OUTPUT_SCREENSHOT_DIR = "outputs/screenshots"
OUTPUT_VIDEO_DIR = "outputs/videos"
